name = "pretty-good-playground-api"
type = "javascript"
zone_id = ""
account_id = "2cd8df55c7a88e252fc16663238a4c84"
route = ""
workers_dev = true
compatibility_date = "2022-04-15"

[dev]
port = 9000

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
dir = "./dist"
main = "./pretty-good-playground-api.es.js" 

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]