name = "http-security-headers"
type = "javascript"
zone_id = ""
account_id = "2cd8df55c7a88e252fc16663238a4c84"
route = ""
workers_dev = true
compatibility_date = "2022-01-09"

[build]
command = "npm run build"
[build.upload]
format = "service-worker"